spring.application.name=spring-boot-webflux
# For Local Dev Env
 spring.data.mongodb.host=127.0.0.1
 spring.data.mongodb.database=webflux
 spring.data.mongodb.port=27017
 spring.data.mongodb.auto-index-creation=true
 
springdoc.api-docs.groups.enabled=true
springdoc.swagger-ui.path=/swagger-doc/swagger-ui.html
springdoc.api-docs.path=/swagger-doc/v3/api-docs 

server.error.include-message=always